---
- name: "Add Node.js from Nodesource"
  shell: "curl -sL https://deb.nodesource.com/setup_{{ node_version }} | sudo -E bash -"
  become: true

- name: "Install Node.js"
  apt:
    name: [nodejs]
    state: latest
  become: true
  update_cache: true

- name: "Install PM2"
  npm:
    name: pm2
    global: yes